workflows:
  android-workflow:
    name: Build Android APK
    environment:
      vars:
        PACKAGE_NAME: "com.naif.istirahat_albarq"
    scripts:
      - name: Fix Flutter project
        script: flutter create --org com.naif .
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
    publishing:
      email:
        recipients:
          - nayfalhetar0@gmail.com
